### ISSUE TITLE
错别字

### ISSUE THREAD

**Issue by tianheg** [ztygcs/ztygcs.github.io#3]
[人的天性是爱好智慧](https://ztygcs.github.io/posts/%E4%BA%BA%E7%9A%84%E5%A4%A9%E6%80%A7%E6%98%AF%E7%88%B1%E5%A5%BD%E6%99%BA%E6%85%A7/) 中“却能继绫存在”存在错别字。

**Comment by ztygcs** [comment]
你好！感谢指出博客中的问题，我修正一下

The end
