### ISSUE TITLE
hugo meme主题 + github pages博客搭建流程，请求指教

### ISSUE THREAD

**Issue by DEROOCE** [ztygcs/ztygcs.github.io#5]
校友你好 :-)
我最近也在尝试使用hugo meme主题搭建博客，但是在与github仓库联结的过程中出现一些问题，google之后也没找到方法。
请问你能否把从初始化到上传整个步骤大致教一下呢？
谢谢！

**Comment by ztygcs** [comment]
你好，加我微信聊吧         


| |
朱聪
|
|
***@***.***
|
签名由网易邮箱大师定制
在2021年3月12日 14:17，Jacob ***@***.***> 写道：
